name: Deploy Nuxt Site to GitHub Pages

on:
  push:
    branches: ["main"] # ou 'master'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- INÍCIO DA CORREÇÃO ---
      # 1. Adicionamos esta etapa para instalar o pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          # Esta flag evita que ele rode 'pnpm install' automaticamente
          # Vamos fazer isso manualmente no próximo passo
          run_install: false 

      # 2. A etapa 'setup-node' agora encontra o pnpm instalado
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # Informa ao setup-node para usar o cache do pnpm
      # --- FIM DA CORREÇÃO ---

      - name: Install Dependencies
        run: pnpm install

      - name: Static Site Generation (SSG)
        run: pnpm generate
        env:
          # Isso continua correto para o seu repositório
          NUXT_APP_BASE_URL: /${{ github.event.repository.name }}/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        